import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync, unlinkSync } from 'node:fs'
import { resolve, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
const run = promisify(execFile)

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const snapshotPath = join(root, '.vitepress/interfaces.json')
const args = process.argv.slice(2)
const check = args.includes('--check')
const sourceIndex = args.indexOf('--source')
if (!(args.length === 0 || (args.length === 1 && check) || (args.length === 2 && sourceIndex === 0 && args[1] && !args[1].startsWith('--')))) {
  throw new Error('Usage: node scripts/interfaces.mjs [--check | --source /path/to/PyLoN]')
}
const banner = '<!-- Generated by scripts/interfaces.mjs; edit the generator or source definitions. -->'
const upstream = 'https://github.com/PyLoN-sim/PyLoN/blob/main/Ros2/pylon_interfaces/'

if (sourceIndex >= 0) {
  const source = resolve(args[sourceIndex + 1])
  const packageRoot = join(source, 'Ros2/pylon_interfaces')
  const cmake = readFileSync(join(packageRoot, 'CMakeLists.txt'), 'utf8')
  const files = [...cmake.matchAll(/"((?:msg|srv)\/[A-Za-z0-9]+\.(?:msg|srv))"/g)].map(match => match[1]).sort()
  if (!files.length || new Set(files).size !== files.length) throw new Error('Missing or duplicate registered interfaces')
  const definitions = Object.fromEntries(files.map(file => [file, readFileSync(join(packageRoot, file), 'utf8')]))
  const revision = (await run('git', ['rev-parse', 'HEAD'], { cwd: source, encoding: 'utf8' })).stdout.trim()
  const modified = Boolean((await run('git', ['status', '--porcelain', '--', 'Ros2/pylon_interfaces'], { cwd: source, encoding: 'utf8' })).stdout.trim())
  writeFileSync(snapshotPath, JSON.stringify({ revision, modified, definitions }, null, 2) + '\n')
}
const snapshot = JSON.parse(readFileSync(snapshotPath, 'utf8'))
const definitions = Object.entries(snapshot.definitions)
const messages = new Set(definitions.filter(([file]) => file.startsWith('msg/')).map(([file]) => file.slice(4, -4)))
const primitives = /^(?:bool|byte|char|float32|float64|u?int(?:8|16|32|64)|string(?:<=\d+)?)$/
const code = value => '`' + value + '`'
const escape = value => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('|', '&#124;')
const expected = new Map()

for (const locale of ['ja', 'en']) {
  const ja = locale === 'ja'
  const prefix = ja ? '' : '/en'
  const directory = join(root, ja ? 'api/interfaces' : 'en/api/interfaces')
  const labels = ja
    ? { fields: 'フィールド', constants: '定数', name: '名前', type: '型', value: '値 / 明示既定値', raw: '元の定義', request: 'Request（リクエスト）', response: 'Response（レスポンス）' }
    : { fields: 'Fields', constants: 'Constants', name: 'Name', type: 'Type', value: 'Value / explicit default', raw: 'Raw definition', request: 'Request', response: 'Response' }
  function typeLink(type) {
    const base = type.replace(/\[.*\]$/, '')
    if (primitives.test(base)) return code(type)
    const parts = base.split('/')
    const name = parts.at(-1)
    const pkg = parts.length === 1 ? 'pylon_interfaces' : parts[0]
    if (pkg === 'pylon_interfaces' && !messages.has(name)) throw new Error(`Unknown message ${type}`)
    const href = pkg === 'pylon_interfaces'
      ? `${prefix}/api/interfaces/msg/${name}`
      : `https://docs.ros.org/en/jazzy/p/${pkg}/msg/${name}.html`
    return `[${code(type)}](${href})`
  }
  function section(raw, title, anchor) {
    const fields = [], constants = []
    for (const original of raw.split('\n')) {
      const line = original.split('#')[0].trim()
      if (!line) continue
      const match = line.match(/^(\S+)\s+([a-zA-Z][a-zA-Z0-9_]*)(?:\s*(=)\s*(.*)|\s+(.+))?$/)
      if (!match) throw new Error(`Unsupported definition line: ${line}`)
      const [, type, name, constant, value, defaultValue] = match
      const row = `| ${code(name)} | ${typeLink(type)} | ${value !== undefined || defaultValue !== undefined ? code(escape(value ?? defaultValue)) : '—'} |`
      ;(constant ? constants : fields).push(row)
    }
    let content = title ? `\n## ${title} {#${anchor}}\n` : ''
    for (const [heading, rows, id] of [[labels.fields, fields, 'fields'], [labels.constants, constants, 'constants']]) {
      if (!rows.length) continue
      content += `\n${title ? '###' : '##'} ${heading} {#${anchor ? anchor + '-' : ''}${id}}\n\n| ${labels.name} | ${labels.type} | ${labels.value} |\n|---|---|---|\n${rows.join('\n')}\n`
    }
    return content
  }
  for (const [file, raw] of definitions) {
    const [kind, filename] = file.split('/')
    const name = filename.slice(0, -4)
    const fullType = `pylon_interfaces/${kind}/${name}`
    let content = `---\neditLink: false\n---\n\n${banner}\n\n# ${fullType} {#pylon-interfaces-${kind}-${name.toLowerCase()}}\n\n`
    content += ja
      ? `[型一覧](${prefix}/api/interfaces/) · [Topic一覧](${prefix}/api/topics) · [上流の${code(filename)}](${upstream}${file})\n\nサイトに保存した定義から生成しています。上流の最新版とは異なる場合があります。[取得元・表記規約](${prefix}/api/interfaces/#conventions)を参照してください。\n`
      : `[Interface index](${prefix}/api/interfaces/) · [Topic reference](${prefix}/api/topics) · [Upstream ${code(filename)}](${upstream}${file})\n\nGenerated from the definitions stored in this site; upstream may differ. See [snapshot provenance and conventions](${prefix}/api/interfaces/#conventions).\n`
    content += `\n\`\`\`bash\nros2 interface show ${fullType}\n\`\`\`\n`
    if (kind === 'srv') {
      const sections = raw.split(/^---\s*$/m)
      if (sections.length !== 2) throw new Error(`Expected request and response in ${file}`)
      content += section(sections[0], labels.request, 'request') + section(sections[1], labels.response, 'response')
    } else content += section(raw)
    content += `\n## ${labels.raw} {#raw-definition}\n\n\`\`\`text\n${raw.trimEnd()}\n\`\`\`\n`
    expected.set(join(directory, kind, `${name}.md`), content)
  }
  let index = `---\neditLink: false\n---\n\n${banner}\n\n# ${ja ? 'メッセージ・サービス型' : 'Message and Service Types'} {#interfaces}\n\n`
  index += ja
    ? 'PyLoN独自のROS 2インターフェースを型ごとに参照できます。各ページはフィールド型、配列の上限、定数、コメントを含む元の定義を掲載します。入れ子のメッセージ型は定義ページへ、標準型はROS 2 Jazzyの公式リファレンスへリンクします。\n'
    : 'Browse each custom PyLoN ROS 2 interface. Pages include field types, array bounds, constants, and the original definition with comments. Nested messages link to their definitions; standard types link to the official ROS 2 Jazzy reference.\n'
  for (const kind of ['msg', 'srv']) {
    index += `\n## ${kind === 'msg' ? 'Messages (.msg)' : 'Services (.srv)'} {#${kind === 'msg' ? 'messages' : 'services'}}\n\n`
    index += definitions.filter(([file]) => file.startsWith(kind + '/')).map(([file]) => {
      const name = file.slice(4, -4)
      return `- [${code(`pylon_interfaces/${kind}/${name}`)}](${prefix}/api/interfaces/${kind}/${name})`
    }).join('\n') + '\n'
  }
  index += ja
    ? '\n## 型の表記と確認方法 {#conventions}\n\nTopicの型は`パッケージ/msg/型名`、サービスは`パッケージ/srv/型名`で表記します。`.msg`内の`geometry_msgs/Point`は`geometry_msgs/msg/Point`、`EngineCommand`は同じパッケージの`pylon_interfaces/msg/EngineCommand`を参照します。\n\n`float64[9]`は固定長9要素、`EngineCommand[<=16]`は最大16要素の可変長配列、`string[]`は上限を指定しない可変長配列です。値の欄の`—`は明示既定値がないことを表します。ROS 2の暗黙の既定値は数値が0、boolがfalse、stringが空文字列、可変長配列が空配列です。定数はフィールドと分けて掲載し、単位・座標系・valid条件などは元の定義のコメントと各APIページで確認できます。型から単位を推測しないでください。\n\nROS環境とPyLoNワークスペースをsourceした後、実際にインストールされた型を次のコマンドで確認できます。\n'
    : '\n## Type notation and inspection {#conventions}\n\nTopic types use `package/msg/TypeName`; service types use `package/srv/TypeName`. Inside `.msg` files, `geometry_msgs/Point` refers to `geometry_msgs/msg/Point`, and `EngineCommand` refers to `pylon_interfaces/msg/EngineCommand` in the same package.\n\n`float64[9]` is a fixed array of nine elements; `EngineCommand[<=16]` is a variable array of at most 16 elements; `string[]` is an unbounded variable array. A `—` in the value column means no explicit default. ROS 2 implicit defaults are zero for numbers, false for bool, an empty string for string, and an empty array for variable arrays. Constants are listed separately from fields. Consult source comments and API pages for units, frames, and validity conditions; a field type alone does not define units.\n\nAfter sourcing ROS and the PyLoN workspace, inspect the installed types with:\n'
  index += '\n```bash\nros2 interface list\nros2 topic type /ksp_vessel/ground_truth/flight\nros2 interface show pylon_interfaces/msg/FlightState\nros2 interface show pylon_interfaces/srv/GetSeparationResult\n```\n\n'
  index += ja
    ? '[ROS 2インターフェース定義の仕様](https://design.ros2.org/articles/legacy_interface_definition.html)に従う表記です。\n\n### 定義の取得元 {#provenance}\n\n'
    : 'Notation follows the [ROS 2 interface definition specification](https://design.ros2.org/articles/legacy_interface_definition.html).\n\n### Snapshot provenance {#provenance}\n\n'
  index += `${code('PyLoN/Ros2/pylon_interfaces')} · Git base: [${code(snapshot.revision.slice(0, 12))}](https://github.com/PyLoN-sim/PyLoN/tree/${snapshot.revision}/Ros2/pylon_interfaces)\n\n`
  index += ja
    ? `${snapshot.modified ? '**取得時のローカル変更を含みます。上記commitそのものの定義ではありません。**' : '上記commitのローカルcheckoutから取得しました。'} サイト内の保存済み定義から生成するため、本体のcloneはサイトのビルドに不要です。インストール済みの版と異なる場合は\`ros2 interface show\`の出力を確認してください。更新手順は[docsのREADME](https://github.com/PyLoN-sim/docs/blob/main/README.md)を参照してください。\n`
    : `${snapshot.modified ? '**Includes local changes at capture time; these are not the exact definitions at the commit above.**' : 'Captured from a local checkout of the commit above.'} Builds use the stored definitions and do not require a clone of PyLoN. If your installed version differs, inspect it with \`ros2 interface show\`. See the [docs README](https://github.com/PyLoN-sim/docs/blob/main/README.md) for update instructions.\n`
  expected.set(join(directory, 'index.md'), index)
}

const stale = []
for (const [path, content] of expected) {
  if (check) {
    if (!existsSync(path) || readFileSync(path, 'utf8') !== content) stale.push(path)
  } else {
    mkdirSync(dirname(path), { recursive: true })
    writeFileSync(path, content)
  }
}
for (const locale of ['', 'en/']) {
  for (const kind of ['msg', 'srv']) {
    const directory = join(root, locale, 'api/interfaces', kind)
    if (!existsSync(directory)) continue
    for (const file of readdirSync(directory)) {
      const path = join(directory, file)
      if (!file.endsWith('.md') || expected.has(path)) continue
      if (check) stale.push(path)
      else if (readFileSync(path, 'utf8').includes(banner)) unlinkSync(path)
      else throw new Error(`Refusing to delete manually authored page: ${path}`)
    }
  }
}
if (stale.length) throw new Error(`Interface pages are stale. Run pnpm run docs:interfaces.\n${stale.join('\n')}`)
console.log(`${check ? 'Checked' : 'Generated'} ${expected.size} interface pages (${messages.size} messages, ${definitions.length - messages.size} services per locale).`)
